import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
  await page.getByText('Username : Admin').click();
  await page.locator('body').press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('A');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('Admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('banner').getByRole('img', { name: 'profile picture' }).click();
  await page.getByRole('link', { name: 'Admin' }).click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).press('CapsLock');
  await page.getByRole('textbox').nth(1).fill('A');
  await page.getByRole('textbox').nth(1).press('CapsLock');
  await page.getByRole('textbox').nth(1).fill('Admin');
  await page.locator('.oxd-select-text').first().click();
  await page.getByRole('option', { name: 'Admin' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).fill('test');
  await page.getByRole('option', { name: 'testuser11 testuser22' }).click();
  await page.locator('div').filter({ hasText: /^-- Select --$/ }).nth(2).click();
  await page.getByRole('option', { name: 'Enabled' }).locator('span').click();
  await page.getByRole('button', { name: 'Search' }).click();
  await expect(page.getByText('Admin').nth(3)).toBeVisible();
  await page.getByRole('button', { name: ' Add' }).click();
  await page.getByText('-- Select --').first().click();
  await page.getByRole('option', { name: 'Admin' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).fill('testuser1241');
  await page.getByText('-- Select --').click();
  await page.getByRole('option', { name: 'Enabled' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).fill('testuser');
  await page.getByText('testuser11 testuser22').click();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('aaaaahsjkaa');
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('@nu');
  await page.getByRole('textbox').nth(3).press('CapsLock');
  await page.getByRole('textbox').nth(3).fill('@nuU');
  await page.getByRole('textbox').nth(3).press('CapsLock');
  await page.getByRole('textbox').nth(3).fill('@nuUr333');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('@nu');
  await page.getByRole('textbox').nth(4).press('CapsLock');
  await page.getByRole('textbox').nth(4).fill('@nuU');
  await page.getByRole('textbox').nth(4).press('CapsLock');
  await page.getByRole('textbox').nth(4).fill('@nuUr333');
  await page.getByRole('button', { name: 'Save' }).click();
  await expect(page.getByText('aaaaahsjkaa')).toBeVisible();
});